version: '3.9'

services:

  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:latest
    ports:
      - "9092:9092"
    restart: always
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_USER:-test}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"


  redis:
    container_name: redis
    restart: always
    image: 'redis:latest'
    ports:
      - "6379:6379"
    logging:
      options:
        max-size: 10m
        max-file: "3"

  service:
    container_name: ride.hailing.service
    image: ride_hailing_service
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py start-service
    ports:
      - "8000:8000"
    environment:
      DATABASE_DRIVER_NAME: 'postgresql+psycopg2'
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: 'changeme'
      DATABASE_HOST: '172.21.0.3'
      DATABASE_PORT: 5432
      DATABASE_NAME: 'Snap'
      DATABASE_POOL_SIZE: 5
      DATABASE_MAX_OVERFLOW: 10
      CACHE_HOST: 'localhost'
      CACHE_PORT: 6379
      CACHE_DB_NUMBER: 0
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000

      KAFKA_BROKERS_LIST: "['localhost:9092']"
      KAFKA_TOPIC: 'RideHailing'
      KAFKA_TOPIC_LIST: "['RideHailing']"
      KAFKA_CONSUMER_GROUP_ID: 'RideHailingConsumerGroup'
      KAFKA_SESSION_TIMEOUT_MS: 6000
      KAFKA_AUTO_OFFSET_RESET: "earliest"

      SCHEDULED_TIME_FOR_CALCULATOR_PROCESS: '* * * * * * */5'











































